# Generated by Django 3.1.5 on 2021-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('request', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256, null=True)),
                ('domain', models.CharField(max_length=64, null=True)),
                ('origin', models.CharField(max_length=256, null=True)),
                ('image', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
