# Generated by Django 3.1.5 on 2021-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='history',
            field=models.TextField(null=True),
        ),
    ]
