# Generated by Django 3.1.5 on 2021-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compare', '0002_image_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='range',
            field=models.IntegerField(null=True),
        ),
    ]
