# Generated by Django 3.1.5 on 2021-04-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compare', '0004_auto_20210427_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='range',
            new_name='rating',
        ),
    ]
